name: CI
# run-name: ${{ github.actor }} ðŸš€
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: mva
      - uses: actions/checkout@v3
        with:
          repository: gentoo-mirror/gentoo
          path: gentoo
      - run: |
          sudo mkdir -p /etc/portage
          echo -e "[DEFAULT]\nmain-repo = gentoo\n\n[gentoo]\nlocation = ${{ github.workspace }}/gentoo\n\n[mva]\nlocation = ${{ github.workspace }}/mva" | sudo tee /etc/portage/repos.conf
          sudo ln -s ${{ github.workspace }}/gentoo/profiles/default/linux/amd64/17.1
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip pkgcheck
      - run: |
          cd mva
          pkgcheck scan --jobs $(nproc) --color true
